spring:
  application:
    name: InfiniteChat-Agent
  profiles:
    active: dev
  mail:
    host: smtp.qq.com  # 以QQ邮箱为例
    port: 587
    username: 1392872725@qq.com # 你的发件账号
    password: rcilakfvmsyaghig # 你的SMTP授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 10010
  servlet:
    context-path: /api


logging:
  level:
    dev.langchain4j.mcp: ERROR

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-0869ebc68c29401fb22c49a81d8e7f36
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-0869ebc68c29401fb22c49a81d8e7f36
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-0869ebc68c29401fb22c49a81d8e7f36

bigmodel:
  api-key: b6292c5bfb75450db4ca9e308e976563.YOSitEmPQV5TyaCd


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

